### ISSUE TITLE
회원가입 기능

### ISSUE THREAD

**Issue by lyr426** [fairy-taler/backend#2]
## 문제제기
- 회원 기능에서 회원가입 기능이 필요

## 기능 요약
- 회원가입 api

## 기능 설명
- 회원가입 api를 호출하면 회원 권한 부여와 DB 갱신 

## 할일 목록
-  [x] 회원 DB 구축 
-  [x] authority 추가 

## 비고
- 여기에 해당 기능에 대한 스크린샷이나 레퍼런스 상세 설명등이 필요한다면 작성해주세요

**Comment by jihi32123** [comment]
잘 보고 있습니다
